export const typeColors: { [key: string]: string } = {
  normal: "bg-gray-400",
  fire: "bg-red-500",
  water: "bg-blue-500",
  electric: "bg-yellow-400",
  grass: "bg-green-500",
  ice: "bg-blue-200",
  fighting: "bg-red-700",
  poison: "bg-purple-500",
  ground: "bg-yellow-600",
  flying: "bg-indigo-400",
  psychic: "bg-pink-500",
  bug: "bg-green-400",
  rock: "bg-yellow-700",
  ghost: "bg-purple-700",
  dragon: "bg-indigo-700",
  dark: "bg-gray-700",
  steel: "bg-gray-400",
  fairy: "bg-pink-300",
};

export const POKEMON_TYPES = [
  "Normal",
  "Fire",
  "Water",
  "Electric",
  "Grass",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
] as const;

export type PokemonType = (typeof POKEMON_TYPES)[number];

// This is a subset of abilities. In reality, there are many more.
export const POKEMON_ABILITIES = [
  "Overgrow",
  "Chlorophyll",
  "Blaze",
  "Solar Power",
  "Torrent",
  "Rain Dish",
  "Shield Dust",
  "Run Away",
  "Shed Skin",
  "Compound Eyes",
  "Swarm",
  "Keen Eye",
  "Tangled Feet",
  "Guts",
  "Intimidate",
  "Static",
  "Lightning Rod",
  "Sand Veil",
  "Arena Trap",
  "Pickup",
  "Technician",
  "Limber",
  "Synchronize",
  "Inner Focus",
  "Magnet Pull",
  "Sturdy",
  "Oblivious",
  "Own Tempo",
  "Suction Cups",
  "Sticky Hold",
  "Cloud Nine",
  "Vital Spirit",
  "Water Absorb",
  "Volt Absorb",
  "Clear Body",
  "Natural Cure",
  "Serene Grace",
  "Swift Swim",
  "Chlorophyll",
  "Illuminate",
  "Trace",
  "Huge Power",
  "Poison Point",
  "Flame Body",
] as const;

export type PokemonAbility = (typeof POKEMON_ABILITIES)[number];
